#!/bin/bash
#
# skript kuupäeva väljastamine.
#
#skript algus
echo "Today is " `date +"%A, %B %dv %Y"` #Väljastab tänase kuupäeva.
echo "Time is "`date +"%H:%M"` #Väljastab hetke kellaja
cal #Väljasstab hetke kalendri kuu
# skripti lõpp
