#!/bin/bash
#Skripti algus
echo -n "Sisesta oma ees- ja perenimi:" #Palve sisestada enda ees ja perenime
read eesnimi perenimi
echo "Sinu eesnimi on $eesnimi ja perenimi on $perenimi" #Väljastab sinu ees ja perenime.
#skripti lõpp

